### ISSUE TITLE
User roles are reset to AUTH_LDAP_SENTRY_ORGANIZATION_ROLE_TYPE after logout

### ISSUE THREAD

**Issue by spawnia** [PMExtra/sentry-auth-ldap#12]
## Steps to reproduce

1. Configure Sentry 23.7.1 with this plugin
2. Set `AUTH_LDAP_SENTRY_ORGANIZATION_ROLE_TYPE = 'member'` in `sentry.conf.py`
3. Login with user A
4. Use a local admin account to assign user A the role `owner`
5. Logout with user A
6. Re-login with user A

## Actual result

The role of user A is reset to `member`.

## Expected result

The role of user A is kept as whatever has been assigned after initial creation.

Please let me know if you need any further information. Thanks for your continued maintenance of this integration.

**Comment by PMExtra** [comment]
Thanks for your feedback. I've understood this issue and found out how it occurred.

https://github.com/PMExtra/sentry-auth-ldap/blob/41fcbc0175edd53a3b2b32583eb34aea63213da0/sentry_auth_ldap/backend.py#L80-L93

Maybe we should add a precondition before line 85.

But I've been busy with my work recently. So, it's welcome for a pull request, or I will dig and fix it over the weekend.
