### ISSUE TITLE
如何安装你这个版本？

### ISSUE THREAD

**Issue by Zian502** [PMExtra/sentry-auth-ldap#15]
#!/bin/bash

requirements=(
'sentry-auth-ldap>=23.6.0'
# You can add other packages here, just like requirements.txt
)

# Install the dependencies of ldap
apt-get update
apt-get install -y --no-install-recommends build-essential libldap2-dev libsasl2-dev

pip install ${requirements[@]}

# Clean up to shrink the image size
apt-get purge -y --auto-remove build-essential
rm -rf /var/lib/apt/lists/*

# Support ldap over tls (ldaps://) protocol
mkdir -p /etc/ldap && echo "TLS_CACERT /etc/ssl/certs/ca-certificates.crt" > /etc/ldap/ldap.conf

**Comment by Zian502** [comment]
有上传到 https://pypi.org/ 吗？

**Comment by PMExtra** [comment]
<img width="925" alt="image" src="https://github.com/PMExtra/sentry-auth-ldap/assets/11289158/6e3e175e-0fcd-49b2-9575-472089ade406">
Please see the README
