### ISSUE TITLE
No organization found

### ISSUE THREAD

**Issue by zahra4fact** [PMExtra/sentry-auth-ldap#17]
I updated my sentry and set ldap as well by following instruction, but after I try to login I face this page
![image](https://github.com/PMExtra/sentry-auth-ldap/assets/35166645/48af0cfb-3d56-48e9-bbc4-aa7d8fcfab0a)

when you click on **please click here** it navigate to our organization sentry, but how I could fix this issue to enter directly to our organization. I set defaul-auth-ldap as well but no difference.

I really appreciate to help me for solving this issue

**Comment by PMExtra** [comment]
Did you set `AUTH_LDAP_SENTRY_DEFAULT_ORGANIZATION` (recommended, organization slug) or `AUTH_LDAP_DEFAULT_SENTRY_ORGANIZATION` (deprecated, organization name)

**Comment by zahra4fact** [comment]
when I set `AUTH_LDAP_SENTRY_DEFAULT_ORGANIZATION` I receive bad gateway

**Comment by PMExtra** [comment]
Take a look at the logs.

**Comment by zahra4fact** [comment]
I solved my problem and I  write it here if someone has the same issue, it is not related to Ldap and it is very simple and funny.

1. Go to organization settings: `https://sentry.example.org/settings/<org slug>/`

2. Change slug, eg. by appending some string

3. Change slug back to original value

ref https://github.com/getsentry/self-hosted/issues/2582#issuecomment-1824442106

Good luck!
