### ISSUE TITLE
Syntax Error in enhance-image.sh example

### ISSUE THREAD

**Issue by Dherlou** [PMExtra/sentry-auth-ldap#3]
Hey there,

thanks for keeping this nice plugin up-to-date. Great work! :)

I noticed a small typo during the installation of this plugin in our new pipeline. There is a syntax error in the enhance-image.sh example in the README.md:
```diff
requirements=(
-sentry-auth-ldap>=21.9.0
+'sentry-auth-ldap>=21.9.0'
# You can add other packages here, just like requirements.txt
)
```
The requirements must be quoted, otherwise bash complains about a syntax error.

**Comment by PMExtra** [comment]
Thank you. I've corrected it.
